### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by fufik** [Kiritow/WarTime-Project#3]
Clear readme can't give me description of this repo? What r u doing?

**Comment by fufik** [comment]
Found a wiki heh

**Comment by Kiritow** [comment]
Sorry but this is the first time for me to use GitHub. I really don't know how to write the README. Could you please teach me something about it?

**Comment by fufik** [comment]
You can save your readme as README.md and then use Markdown to make it more beautiful.

**Comment by Kiritow** [comment]
Good idea. Thanks ~
